baseURL = "https://shusheaan.github.io/"
languageCode = "en-us"
title = "CYANED"
theme = "hugo-paper"

staticDir = ["static"]

[menu]
    [[menu.main]]
    identifier = 'intro'
    name       = 'Intro'
    url        = '/intro'
    weight     = 0

    [[menu.main]]
    identifier = "channels"
    name       = "Channels"
    url        = "/channels/"
    weight     = 1
